# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a5dc1788e0f42be62df63c62184efd87c9fbd6ab6fd2f1ac62f9d1825f95313a19e0b03c971aed30e6437abe9d2d67056d7455253a44b0e6c0af4b567ea29674

test:
  secret_key_base: 8c706ad64b3e4d8d08ec0ff2e4a56c682e52226a547493a74f533948a4aab7a590ab959174b4c2583ffa959ec6911b52ffd9b75ecbd975e6bb51a114ab9e3013

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
